---
summary: Build the Gitlab webhook.

description: |
  The `build` task builds the Gitlab webhook in the current
  directory.

  This task runs in a Linux container. If working on Mac OS
  make sure to set GOOS appropriately.

image: golang:1.11-stretch

mount: /go/src/gitlab.com/run-ci/webhooks/gitlab

command: go build -v

arguments:
  GOOS:
    description: Platform to build for.
    default: linux
